LIBS=-l1 -lantlr3c
a.out: main.c lib2.c
	${CC} -g $^ -L /home/iamnotagenius/Sources/spo_labs/libantlr3c-3.4/lib/lib -L/home/iamnotagenius/Sources/spo_labs/lab1/lib -Wl,-rpath=/home/iamnotagenius/Sources/spo_labs/lab1/lib:/home/iamnotagenius/Sources/spo_labs/libantlr3c-3.4/lib/lib $(LIBS)
